feat(PDS-70): publish storybook
mia-platform/design-system pull request #200
Opened 2023-11-30 14:35 UTC by Giogia

### Description

Added Github workflow to publish Storybook on GH pages

##### Storybook

Added Github workflow to publish Storybook on GH pages

### Issue ticket number and link

[PDS-70](https://makeitapp.atlassian.net/browse/PDS-70?atlOrigin=eyJpIjoiODkxMmYwZTg3N2QyNDQ2OGFiZWExZmI5MDE3Mjg3ZDUiLCJwIjoiaiJ9)

### Checklist

- [x] added the link to the Jira task
- [x] commit message and branch name follow conventions
- [ ] tests are included
- [ ] changes are accessible and documented from components stories
- [ ] typings are updated or integrated accordingly with your changes
- [ ] all added files include Apache 2.0 license
- [ ] the changelog has been updated accordingly with your changes
- [x] you are not committing extraneous files or sensible data
- [ ] the browser console does not have any logged errors

2023-11-30 16:07 UTC, Danielecina approved these changes

2023-12-04 17:22 UTC, davidebianchi requested changes

2023-12-04 17:22 UTC, davidebianchi commented on .github/workflows/storybook.yml
> +      - run: yarn build-storybook
To run yarn, we should configure node

2023-12-06 11:15 UTC, Giogia commented on .github/workflows/storybook.yml
> +      - run: yarn build-storybook
added :heavy_check_mark:

2023-12-06 11:50 UTC, Danielecina approved these changes

2023-12-06 15:02 UTC, davidebianchi approved these changes
LGTM

2023-12-06 15:02 UTC, merged